spring.application.name=backend
spring.application.name=Backend
spring.datasource.url=jdbc:postgresql://localhost:5432/UsersDb
spring.datasource.username=postgres
spring.datasource.password=yaar2121

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.port=8081
